name: Fix Lockfile on Dependency Updates

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  update-lockfile:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          submodules: true
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Check last commit author
        id: renovate-check
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          EMAIL=$(git log -1 --pretty=format:'%ae')
          COMMIT=$(git log -1 --pretty=format:'%H')

          echo "Detected commit author: $AUTHOR"
          echo "Detected commit email: $EMAIL"
          echo "Commit SHA: $COMMIT"

          echo "author=$AUTHOR" >> $GITHUB_OUTPUT

      - name: Stop if last commit not from Renovate
        if: steps.renovate-check.outputs.author != 'renovate[bot]'
        run: |
          echo "Last commit not from Renovate, skipping."

      - name: Install Deno
        if: steps.renovate-check.outputs.author == 'renovate[bot]'
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Update lock file
        if: steps.renovate-check.outputs.author == 'renovate[bot]'
        run: deno install
        shell: bash

      - name: Commit changes if needed
        if: steps.renovate-check.outputs.author == 'renovate[bot]'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"

          if [[ -n "$(git status --porcelain deno.lock)" ]]; then
            git add deno.lock
            git commit -m "Auto-update deno.lock"
            git push origin HEAD:${{ github.head_ref }}

            echo "Requesting Renovate to keep this PR updated"
            gh pr edit ${{ github.event.pull_request.number }} --add-label keep-updated
          else
            echo "No change in lockfile."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
